/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArscImpl */

#ifndef _Included_LsmImpl
#define _Included_LsmImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArscImpl
 * Method:    initContext
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_LsmImpl_initContext
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ArscImpl
 * Method:    finishContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LsmImpl_finishContext
  (JNIEnv *, jobject);

/*
 * Class:     ArscImpl
 * Method:    signMessage
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_LsmImpl_signMessage
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     ArscImpl
 * Method:    unsignMesage
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_LsmImpl_unsignMesage
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     ArscImpl
 * Method:    LsmImplCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LsmImpl_LsmImplCreate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
